###
GET http://localhost:8000/api/users/

###
DELETE  http://localhost:8000/api/users/delete/61eeed0529e69c19c5bd387f

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Jorge Vivas",
    "email":"jore@gmail.com",
    "password":"abcabc"
}

###
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "email":"jore1@gmail.com",
    "password":"abcabca"
}

###
GET http://localhost:8000/api/videogame/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA
###3e62a54c727560927c
DELETE  http://localhost:8000/api/videogame/delete/61e3e902c69f3dc760985943
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA

###
POST http://localhost:8000/api/videogame/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA

{
        "name":"Fifa 22",
        "url_image":"https://media.rawg.io/media/games/355/355d2ec5d6b87518228dc30a9bb0e70d.jpg",
        "status":"Not Started",
        "userId":"61e15ba0b0cf86faac9b4cd0"
         
}
###
GET http://localhost:8000/api/videogame/list/61efb54a9e4693215aadc52d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA

###
/* "description":"Juego de futbol",
        "ranting":8,
        "image":"aaa",
        "plattaform":"pc",
        "personalComment":"increible",
        "personalRating":10,
        "state":"in progress",
         "userId": "61e15ba0b0cf86faac9b4cd0"*/

###
DELETE  http://localhost:8000/api/videogame/delete/61efb54a9e4693215aadc52d/61efb5de9e4693215aadc546
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA
###
GET http://localhost:8000/api/videogame/game/61e15ba0b0cf86faac9b4cd0/61ee5dd3c63f44c8ad593e56
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA

###
PUT http://localhost:8000/api/videogame/update/61ee841891eed7b28ea90d2e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA
Content-Type: application/json

{
    "rating":4,
    "comment":"Con ganas de mejorar en Fut Champions",
    "status":"In Progress"
}