###
GET http://localhost:8000/api/users/

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Jorge Vivas",
    "email":"jore@gmail.com",
    "password":"abcabc"
}

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Alberto Rodriguez",
    "email":"alber@gmail.com",
    "password":"abcabcabc"
}

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Ana Rodriguez",
    "email":"Ana@gmail.com",
    "password":"abcabcabc"
}

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"alicia Rodriguez",
    "email":"ali@gmail.com",
    "password":"123456"
}


###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Marta Ruiz",
    "email":"marta@gmail.com",
    "password":"holacarapan4"
}
###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Pedro Ruiz",
    "email":"maa@gmail.com",
    "password":"holacarap"
}
###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Jaime Moro",
    "email":"Moro@gmail.com",
    "password":"holacarap"
}

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Pedro Ramirez",
    "email":"pedrito@gmail.com",
    "password":"holacarap"
}

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"Cathow",
    "email":"cathow@gmail.com",
    "password":"gato"
}

###
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
    "name":"pera23",
    "email":"pera23@gmail.com",
    "password":"gato"
}

###
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "email":"jore10@gmail.com",
    "password":"abcabc"
}

###
GET http://localhost:8000/api/videogame/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA
###3e62a54c727560927c
DELETE  http://localhost:8000/api/videogame/delete/61e3e902c69f3dc760985943
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA

###
POST http://localhost:8000/api/videogame/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA

{
        "name":"Fifa 22",
        "url_image":"https://media.rawg.io/media/games/355/355d2ec5d6b87518228dc30a9bb0e70d.jpg",
        "status":"Not Started",
        "userId":"61e15ba0b0cf86faac9b4cd0"
         
}
###
GET http://localhost:8000/api/videogame/list/61e15ba0b0cf86faac9b4cd0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA

###
/* "description":"Juego de futbol",
        "ranting":8,
        "image":"aaa",
        "plattaform":"pc",
        "personalComment":"increible",
        "personalRating":10,
        "state":"in progress",
         "userId": "61e15ba0b0cf86faac9b4cd0"*/

###
DELETE  http://localhost:8000/api/videogame/delete/61e15ba0b0cf86faac9b4cd0/61e5a31d6730d3f53890dfd4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTE1YmEwYjBjZjg2ZmFhYzliNGNkMCIsImVtYWlsIjoiam9yZTEwQGdtYWlsLmNvbSIsImlhdCI6MTY0MjI3MjM2Nn0.YQVhNlUcUGLT919ppZK1OvVUUvRR6pTPZCDmdzEkBAA